# Generated by Django 6.0.2 on 2026-02-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alunos_matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nasc', models.DateField()),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
