# Generated by Django 6.0.2 on 2026-02-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunos_matricula',
            old_name='data_nasc',
            new_name='dataNasc_aluno',
        ),
        migrations.RenameField(
            model_name='alunos_matricula',
            old_name='nome',
            new_name='nome_aluno',
        ),
    ]
