# Generated by Django 6.0.2 on 2026-02-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_matricula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alunos_matricula',
        ),
    ]
