# Generated by Django 6.0.2 on 2026-03-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_delete_alunos_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='quemResponsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
