# Generated by Django 6.0.3 on 2026-03-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_matricula_quemresponsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='cepAluno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='descricaoAlergia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='descricaoBeneficio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='descricaoLaudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='tipoResponsavel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='alergiaAluno',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='laudoAluno',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='recebeBeneficioAluno',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=10, null=True),
        ),
    ]
