# Generated by Django 6.0.3 on 2026-03-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='declaração',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoAluno', models.CharField(max_length=255)),
                ('nacionaliadeAluno', models.CharField(blank=True, max_length=100, null=True)),
                ('natularidadeAluno', models.CharField(blank=True, max_length=100, null=True)),
                ('ufAluno', models.CharField(blank=True, max_length=10, null=True)),
                ('dataNascimentoAluno', models.DateField(blank=True, null=True)),
                ('sexoDoAluno', models.CharField(blank=True, max_length=20, null=True)),
                ('turmaDoAluno', models.CharField(blank=True, max_length=50, null=True)),
                ('cartaoSusDoAluno', models.CharField(blank=True, max_length=30, null=True)),
                ('cpfDoAluno', models.CharField(blank=True, max_length=14, null=True)),
                ('nomePai', models.CharField(blank=True, max_length=255, null=True)),
                ('nomeMae', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
