# Generated by Django 6.0.3 on 2026-03-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioSec', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='declaração',
            new_name='declaracao',
        ),
    ]
